### ISSUE TITLE
Fix some issues

### ISSUE THREAD

**Issue by howff** [BehaviouralInsights/BIT-ADRUK-synthetic-data-tool#3]
I've opened a PR to fix some issues such as
* dates not being recognised
* times having different precision than the original
* integers not being output
* logical AND statements wrong

**Comment by howff** [comment]
An observation - having an int column with NAs is problematic in several respects. Pandas 2.4 is supposed to make this easier but it's not out yet.

Some changes have been made to make it more compatible with newer numpy/pandas, such as changing `NaN` to `nan`.

One change which has not been made yet is `applymap` is deprecated and they suggest using `apply` instead. I've not made this change because I'm not sure of the implications.

**Comment by howff** [comment]
I have tested replacing `applymap` with `map` and it seems to work ok

**Comment by IOThomas** [comment]
Thanks again for all these suggestions -- I've reviewed them and have attached a few comments/questions to two of them before I go ahead with the merge.
